name: Branch Management

on:
  push:
    branches:
      - 'main'
jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Merge to Main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git push origin main

  test:
    needs: merge-to-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          # Aquí deberías poner tus comandos para ejecutar las pruebas
          echo "Ejecutando pruebas..."
          # Por ejemplo: npm test
